extends:
    - stylelint-config-standard
rules:
    no-duplicate-selectors: false
    function-name-case: "lower"
    string-quotes: "double"
    property-case: "lower"
    selector-pseudo-class-case: "lower"
    selector-pseudo-element-case: "lower"
    selector-type-case: "lower"
    unit-case: "lower"
    value-keyword-case: "lower"
