# We plan on using one workflow to run all the jobs (build, test, linting, and documentation)
name: CI/CD Pipeline

# The workflow will be activated on every pull request made to main and every push made to [main, Unit-Testing] branches
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '*'

# All of our jobs will be tested on ubuntu-latest and node versions [10.x, 12.x, 14.x, 15.x]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
    - uses: actions/checkout@v2
    - name: npm install and build webpack
      run:
        npm install
        npm run build --if-present
    # Tests are currently being implemented in the Unit-Testing branch. It will be merge once they're stable
#   test:
#     needs: build
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [10.x, 12.x, 14.x, 15.x]
#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v2
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: Install npm dependencies
#         run:
#           npm install
#       - name: Install jest
#         run:
#           npm install --save-dev jest
#       - name: Install execa for e2e testing
#         run:
#           npm install --save execa
#       - name: Install babel
#         run:
#           npm install --save-dev jest babel-jest @babel/core @babel/preset-env
#       - name: Run tests
#         run:
#           npm run test
          
          
  styling:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Super-Linter 
        uses: github/super-linter@v3
        env:
          LINTER_RULES_PATH: '.'
          FILTER_REGEX_INCLUDE: .*sources/.*
          CSS_FILE_NAME: .stylelintrc.yml
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.yml
          
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build doc generation
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./sources
          recurse: true
          output_dir: ./specs/docs
      - uses: actions/upload-artifact@main
        with:
          name: documentation
          path: ./specs/docs

